#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QStatusBar>
#include <QSystemTrayIcon>
#include <QMenu>
#include <QAction>
#include <QMessageBox>
#include <QCloseEvent>
#include <QSettings>
#include <QDir>
#include <QDateTime>
#include "screen.h"
#include "inputwebsocket.h"
#include "constants.h"
#include "windows.h"

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();
    QVariant readSettings(QString key);
    void writeToRegistry(QString key, QVariant value);
    void loadSettingsFromRegistry();
    bool nativeEvent(const QByteArray& eventType, void* message, long* result);
    void log(const QString &logtext);
    void setupCombobox(QVector<DISPLAY_DEVICE> displays);
    void setupTooltips();
    void setupHotkeys();
    QString timestamp();

private slots:
    void onStatusReceived(QString status);
    //Following names generated by MOC, don't rename!
    void on_pbToLandscape_clicked();
    void on_pbToPortrait_clicked();
    void on_pbToLandscapeFlipped_clicked();
    void on_pbToPortraitFlipped_clicked();
    void on_lineEditWebSocketAddr_returnPressed();
    void on_checkBoxAutostart_stateChanged(int state);
    void on_comboBoxDisplayList_activated(int index);

private:
    Ui::MainWindow *ui;
    Screen *scr;
    InputWebSocket *iWebSocket;
    QString statusMsg;
    QSystemTrayIcon *sysTrayIcon;
    bool closing;
    bool firstStart;
    bool firstHide = true;
    void setupSysTray();

protected:
    void closeEvent(QCloseEvent *event);
};

#endif // MAINWINDOW_H
